---
title: Lecture 2 - Note
subtitle: ggplot Basics
author: 
  - name: Byeong-Hak Choe
date: 2024-02-02

execute: 
  echo: true    # true false
  eval: true    # true false
  warning: false    # true false
  message: false    # true false
  fig-width: 9
  # fig-height: 5
  
format: 
  html:
    toc: true    # true false
    number-sections: true    # true false
    code-fold: false    # true false show       # https://quarto.org/docs/output-formats/html-code.html
    code-tools: true    # true false
    highlight-style: atom-one        # atom-one tango espresso   # https://quarto.org/docs/output-formats/html-code.html#highlighting
    
---

```{r setup}
#| include: false

library(tidyverse)
library(skimr)
library(ggthemes)
library(hrbrthemes)
library(DT)

theme_set(theme_ipsum()+
          theme(strip.background =element_rect(fill="lightgray"),
                axis.title.x = 
                  element_text(angle = 0,
                               size = rel(1.33),
                               margin = margin(10,0,0,0)),
                axis.title.y = 
                  element_text(angle = 90,
                               size = rel(1.33),
                               margin = margin(0,10,0,0))
                )
          )
```



# Make a plot!
To add a code chunk,
  - Alt + Ctrl + I
  - option + command + I


To run a code chunk
  - Ctrl + Shift + Enter
  - command + shift + return
  
To run a current line of code
  - Ctrl + Enter
  - command + return
```{r}
library(gapminder)
gapminder <- gapminder::gapminder
skim(gapminder)

```


```{r}
#| echo: false
datatable(gapminder)
```


```{r}
p <- ggplot(data = gapminder,
            aes(x = gdpPercap, y = lifeExp))
```

Below is the scatter plot of `gdpPercap` vs. `lifeExp`

```{r}
p + geom_point()
```

Let's add a curve that fits into the data points.

```{r}
#| message: false
p + geom_point() +
  geom_smooth()
```


```{r}
#| message: false
p + geom_point() +
  geom_smooth() +
  geom_smooth(method = lm)
```



```{r}
p1 <- ggplot(data = gapminder,
             mapping = aes(x = gdpPercap, y = lifeExp,
                           color = continent))
```

```{r}
p1 + geom_point()
```

```{r}
p + geom_point(color = "red")
```


```{r}
p + geom_point(color = "purple") +
  geom_smooth(method = lm)
```


```{r}
p + geom_point(alpha = .2, size = 10)
```


```{r}
p + geom_point(alpha = .2) +
  geom_smooth(method = lm,
              color = "orange",
              se = F,
              linewidth = 10
              )

```


```{r}
p + geom_point(alpha = .25) +
  geom_smooth() +
  scale_x_log10(labels = scales::dollar) +
  labs(x = "GDP Per Capita", y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")
```



```{r}
p1 + geom_point(alpha = .25) +
  geom_smooth() +
  scale_x_log10(labels = scales::dollar) +
  labs(x = "GDP Per Capita", y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")

```

```{r}
#| fig-height: 9
p1 + geom_point(alpha = .25) +
  geom_smooth() +
  geom_smooth(method = lm) +
  guides(color = "none") +
  facet_wrap( . ~ continent ) +
  scale_x_log10(labels = scales::dollar) +
  labs(x = "GDP Per Capita", y = "Life Expectancy in Years",
         title = "Economic Growth and Life Expectancy",
         subtitle = "Data points are country-years",
         caption = "Source: Gapminder.")


```


```{r}
p + geom_point(alpha = .25,
               aes(color = continent)) +
  geom_smooth(  )
```

```{r}
p_out <- p + geom_point(alpha = .25) +
  geom_smooth() +
  scale_x_continuous(trans = scales::log_trans())  # natural log
p_out

# ggsave("my_figure.pdf", plot = p_out)

```

<br>


# References

- [R for Data Science](http://r4ds.hadley.nz) by [Hadley Wickham](https://hadley.nz)

